### ISSUE TITLE
Clear displays when there's no data

### ISSUE THREAD

**Issue by mairas** [mxtommy/SigkSens-webapp#1]
I was playing with your displays and have to say they're pretty impressive! Definitely something I'll try out next summer.

One thing I noticed, though. When I killed power to the sensor and NMEA bus, the gauges kept on showing the readings. Could you add a timer to the gauges so that they'd indicate lack of data if they've stopped updating?

**Comment by mxtommy** [comment]
I think you're talking about kip? :P (I opened a new issue here: https://github.com/mxtommy/Kip/issues/10 )
